[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "1.5.2"
python = "3.10.4"
scipy = "*"
matplotlib = "3.6.2"
seaborn = "0.12.2"
numpy = "1.24.1"
